name: Docker Image CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: | 
        docker login
        export TAG="rejection-letter-detection:$(date +%s)"
        docker build . --file Dockerfile --tag ${TAG}
        docker image ls
        docker push ${TAG}
      
